In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [136]:
class RestrictedBoltzmannMachine:
    def __init__(self, n_visible, n_hidden):
        self.n_visible = n_visible
        self.n_hidden = n_hidden
        # self.visible_layer = np.zeros(n_visible)
        # self.hidden_layer = np.random.random(size=n_hidden)
        # self.weights = np.random.rand(n_visible, n_hidden)
        self.visible_layer = np.array([0.25, 0.72])
        self.hidden_layer = np.array([0.87, 0.14, 0.64])
        self.weights = np.array([[2, -1, 1], [-2, 0, -1]])

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def reconstruct_hidden_layer(self, visible_input):
        # Calculate hidden probabilities
        hidden_probas = []
        for j in range(self.n_hidden):
            hidden_probas += [self.sigmoid(sum([visible_input[i]*self.weights[i][j] for i in range(self.n_visible)]))]
        # Sample hidden layer output from calculated probabilties
        return (np.random.random(size=self.n_hidden) < hidden_probas).astype(int)

    def reconstruct_visible_layer(self, hidden_input):
        # Calculate visible probabilities
        visible_probas = []
        for i in range(self.n_visible):
            visible_probas += [self.sigmoid(sum([hidden_input[j]*self.weights[i][j] for j in range(self.n_hidden)]))]
        # Sample visible layer output from calculated probabilties
        return (np.random.random(size=self.n_visible) < visible_probas).astype(int)
    
    def train(self, patterns, eta=0.01):
        for v in patterns:
            # Take training sample, and comput probabilties of hidden units and the
            # sample a hidden activation vector from this probability distribution
            h = self.reconstruct_hidden_layer(v)

            # Compute the outer product of v and h and call this the positive gradient
            pos_grad = np.outer(v, h)

            # From h, sample a reconstruction v' of the visible units
            v_prime = self.reconstruct_visible_layer(h)

            # Then resample activations h' from this
            h_prime = self.reconstruct_hidden_layer(v_prime)

            # Compute the outer product of v' and h' and call this the negative gradient
            neg_grad = np.outer(v_prime, h_prime)
            print(pos_grad)
            print(neg_grad)
            print('='*100)

            # The update to the weight matrix W, will be the positive gradient minus the negative gradient, times some learning rate
            W_delta = eta*(pos_grad.T - neg_grad.T)
            print(W_delta)

    def recall(self, pattern, n_gibbs):
        pass

In [137]:
rbm = RestrictedBoltzmannMachine(2, 3)
rbm.train([[1,1]])

[[1 0 1]
 [1 0 1]]
[[1 0 1]
 [0 0 0]]
[[0.   0.01]
 [0.   0.  ]
 [0.   0.01]]


In [118]:
t = np.array([
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1,  1,  1,  1],
        [-1, -1, -1, -1, -1, -1,  1,  1, -1,  1],
        [-1, -1, -1, -1, -1,  1,  1,  1, -1,  1],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
    ])