In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [167]:
class RestrictedBoltzmannMachine:
    def __init__(self, n_visible, n_hidden):
        self.n_visible = n_visible
        self.n_hidden = n_hidden
        self.W = np.random.rand(n_visible, n_hidden)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def reconstruct_hidden_layer(self, visible_input):
        # Calculate hidden probabilities
        activation = np.vectorize(self.sigmoid)
        hidden_probas = activation(np.inner(visible_input, self.W.T))

        # Sample hidden layer output from calculated probabilties
        return (np.random.random(size=self.n_hidden) < hidden_probas).astype(int)

    def reconstruct_visible_layer(self, hidden_input):
        # Calculate visible probabilities
        activation = np.vectorize(self.sigmoid)
        visible_probas = activation(np.inner(hidden_input, self.W))

        # Sample visible layer output from calculated probabilties
        return (np.random.random(size=self.n_visible) < visible_probas).astype(int)
    
    def train(self, patterns, eta=0.01):
        for v in patterns:
            # Take training sample, and comput probabilties of hidden units and the
            # sample a hidden activation vector from this probability distribution
            h = self.reconstruct_hidden_layer(v)

            # Compute the outer product of v and h and call this the positive gradient
            pos_grad = np.outer(v, h)

            # From h, sample a reconstruction v' of the visible units
            v_prime = self.reconstruct_visible_layer(h)

            # Then resample activations h' from this
            h_prime = self.reconstruct_hidden_layer(v_prime)

            # Compute the outer product of v' and h' and call this the negative gradient
            neg_grad = np.outer(v_prime, h_prime)
            print(pos_grad)
            print(neg_grad)
            print('='*100)

            # The update to the weight matrix W, will be the positive gradient minus the negative gradient, times some learning rate
            W_delta = eta*(pos_grad.T - neg_grad.T)
            print(W_delta)

    def recall(self, pattern, n_gibbs):
        pass

In [168]:
rbm = RestrictedBoltzmannMachine(2, 3)
rbm.train([[1,1]])

hidden_probas = [0.6390831  0.83490359 0.80403029]
visible_probas = [0.78120513 0.85317965]
hidden_probas = [0.6390831  0.83490359 0.80403029]
[[0 1 1]
 [0 1 1]]
[[1 1 1]
 [1 1 1]]
[[-0.01 -0.01]
 [ 0.    0.  ]
 [ 0.    0.  ]]


In [118]:
t = np.array([
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1,  1,  1,  1],
        [-1, -1, -1, -1, -1, -1,  1,  1, -1,  1],
        [-1, -1, -1, -1, -1,  1,  1,  1, -1,  1],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
    ])